language: node_js
node_js:
  - '0.10'
  - '0.11'
env:
  global:
    - SAUCE_USERNAME=fullstack_ci
    - SAUCE_ACCESS_KEY=1a527ca6-4aa5-4618-86ce-0278bf158cbf
addons:
  sauce_connect: true
before_install:
  - gem update --system
  - gem install sass --version "=3.3.7"
  - npm install -g bower grunt-cli
services: mongodb
